symbols = [
    "US$",
    "$",
    "AED",
    "EGP",
    "SAR",
    "KR",
    "₪",
    "€",
    "£",
    "¥",
    "₱",
    "RM",
    "Rp",
    "₹",
    "LKR",
    "IDR",
    "TWD",
    "HKD",
]

country_names = {
    "ABW": "Aruba",
    "AFG": "Afghanistan",
    "AGO": "Angola",
    "ALB": "Albania",
    "AND": "Andorra",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ASM": "American Samoa",
    "ATG": "Antigua and Barbuda",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgaria",
    "BHR": "Bahrain",
    "BHS": "Bahamas",
    "BIH": "Bosnia and Herzegovina",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BMU": "Bermuda",
    "BOL": "Bolivia",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "BRN": "Brunei",
    "BTN": "Bhutan",
    "BWA": "Botswana",
    "CAF": "Central African Republic",
    "CAN": "Canada",
    "CHE": "Switzerland",
    "CHL": "Chile",
    "CHN": "China",
    "CIV": "Côte d'Ivoire",
    "CMR": "Cameroon",
    "COD": "Democratic Republic of the Congo",
    "COG": "Republic of the Congo",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cape Verde",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CYM": "Cayman Islands",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DEU": "Germany",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DNK": "Denmark",
    "DOM": "Dominican Republic",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ERI": "Eritrea",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FIN": "Finland",
    "FJI": "Fiji",
    "FLK": "Falkland Islands",
    "FRA": "France",
    "FRO": "Faroe Islands",
    "FSM": "Micronesia",
    "GAB": "Gabon",
    "GBR": "United Kingdom",
    "GEO": "Georgia",
    "GGY": "Guernsey",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinea",
    "GMB": "Gambia",
    "GNB": "Guinea-Bissau",
    "GNQ": "Equatorial Guinea",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GRL": "Greenland",
    "GTM": "Guatemala",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HKG": "Hong Kong",
    "HND": "Honduras",
    "HRV": "Croatia",
    "HTI": "Haiti",
    "HUN": "Hungary",
    "IDN": "Indonesia",
    "IMN": "Isle of Man",
    "IND": "India",
    "IRL": "Ireland",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KHM": "Cambodia",
    "KIR": "Kiribati",
    "KNA": "Saint Kitts and Nevis",
    "KOR": "South Korea",
    "KWT": "Kuwait",
    "LAO": "Laos",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LCA": "Saint Lucia",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LSO": "Lesotho",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "MAC": "Macao",
    "MAF": "Saint Martin",
    "MAR": "Morocco",
    "MCO": "Monaco",
    "MDA": "Moldova",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MHL": "Marshall Islands",
    "MKD": "North Macedonia",
    "MLI": "Mali",
    "MLT": "Malta",
    "MMR": "Myanmar",
    "MNE": "Montenegro",
    "MNG": "Mongolia",
    "MNP": "Northern Mariana Islands",
    "MOZ": "Mozambique",
    "MRT": "Mauritania",
    "MSR": "Montserrat",
    "MTQ": "Martinique",
    "MUS": "Mauritius",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MYT": "Mayotte",
    "NAM": "Namibia",
    "NCL": "New Caledonia",
    "NER": "Niger",
    "NFK": "Norfolk Island",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niue",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "NPL": "Nepal",
    "NRU": "Nauru",
    "NZL": "New Zealand",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PCN": "Pitcairn",
    "PER": "Peru",
    "PHL": "Philippines",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "PRI": "Puerto Rico",
    "PRK": "North Korea",
    "PRT": "Portugal",
    "PRY": "Paraguay",
    "PSE": "Palestine",
    "PYF": "French Polynesia",
    "QAT": "Qatar",
    "REU": "Réunion",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SAU": "Saudi Arabia",
    "SDN": "Sudan",
    "SEN": "Senegal",
    "SGP": "Singapore",
    "SGS": "South Georgia",
    "SHN": "Saint Helena",
    "SJM": "Svalbard and Jan Mayen",
    "SLB": "Solomon Islands",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SMR": "San Marino",
    "SOM": "Somalia",
    "SPM": "Saint Pierre and Miquelon",
    "SRB": "Serbia",
    "SSD": "South Sudan",
    "STP": "Sao Tome and Principe",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SWE": "Sweden",
    "SWZ": "Eswatini",
    "SXM": "Sint Maarten",
    "SYC": "Seychelles",
    "SYR": "Syria",
    "TCA": "Turks and Caicos Islands",
    "TCD": "Chad",
    "TGO": "Togo",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKL": "Tokelau",
    "TKM": "Turkmenistan",
    "TLS": "Timor-Leste",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TUV": "Tuvalu",
    "TWN": "Taiwan",
    "TZA": "Tanzania",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "UMI": "United States Minor Outlying Islands",
    "URY": "Uruguay",
    "USA": "United States",
    "UZB": "Uzbekistan",
    "VAT": "Vatican City",
    "VCT": "Saint Vincent and the Grenadines",
    "VEN": "Venezuela",
    "VGB": "British Virgin Islands",
    "VIR": "United States Virgin Islands",
    "VNM": "Vietnam",
    "VUT": "Vanuatu",
    "WLF": "Wallis and Futuna",
    "WSM": "Samoa",
    "XKX": "Kosovo",
    "YEM": "Yemen",
    "ZAF": "South Africa",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
    "AFE": "Africa Eastern",
    "AFW": "Africa Western",
    "AFR": "Africa",
    "ARB": "Arab World",
    "BEA": "Benin",
    "BEC": "Belgium",
    "BHI": "Bahrain",
    "BLA": "Bolivia",
    "BMN": "Bermuda",
    "BSS": "South Sudan",
    "CAA": "Canada",
    "CEA": "Central Europe",
    "CEB": "Central Europe and Baltics",
    "CEU": "European Union",
    "CLA": "Chile",
    "CME": "Cameroon",
    "CSA": "Czech Republic",
    "CSS": "Czech Republic",
    "DEA": "Germany",
    "DEC": "Germany",
    "DLA": "Dominica",
    "DMN": "Dominican Republic",
    "DNS": "Denmark",
    "DSA": "Dominica",
    "DSF": "Dominican Republic",
    "DSS": "Dominican Republic",
    "EAP": "East Asia & Pacific",
    "EAR": "Early",
    "EAS": "East Asia",
    "ECA": "Europe & Central Asia",
    "ECS": "Ecuador",
    "EMU": "Euro area",
    "EUU": "European Union",
    "FCS": "Fragile and Conflict Affected States",
    "FXS": "France",
    "HIC": "High income",
    "HPC": "High income",
    "IBB": "IBRD",
    "IBD": "IBRD",
    "IBT": "IBRD",
    "IDA": "IDA",
    "IDB": "IDA",
    "IDX": "IDA",
    "INX": "India",
    "LAC": "Latin America & Caribbean",
    "LCN": "Latin America",
    "LDC": "Least developed countries",
    "LIC": "Low income",
    "LMC": "Lower middle income",
    "LMY": "Lower middle income",
    "LTE": "Lithuania",
    "MDE": "Moldova",
    "MEA": "Middle East & North Africa",
    "MIC": "Middle income",
    "MNA": "Middle East & North Africa",
    "NAC": "North America",
    "NAF": "North Africa",
    "NRS": "Nepal",
    "NXS": "Netherlands",
    "OED": "OECD members",
    "OSS": "Other small states",
    "PRE": "Pre",
    "PSS": "Pacific Island small states",
    "PST": "Pacific Island small states",
    "RRS": "Russia",
    "SAS": "South Asia",
    "SSA": "Sub-Saharan Africa",
    "SSF": "Sub-Saharan Africa",
    "SST": "Small states",
    "SXZ": "Sint Maarten",
    "TEA": "Turkey",
    "TEC": "Turkey",
    "TLA": "Timor-Leste",
    "TMN": "Turkmenistan",
    "TSA": "Tonga",
    "TSS": "Tonga",
    "UMC": "Upper middle income",
    "WLD": "World",
    "XZN": "Zambia",
}

EXCHANGE_RATES = {
    "USD": 1.0,
    "LKR": 300.0,
    "IDR": 15500.0,
    "TWD": 32.0,
    "HKD": 7.8,
    "PHP": 56.0,
    "JPY": 158.77,
    "EUR": 0.87,
    "GBP": 0.75,
    "KRW": 1350.0,
    "MYR": 4.7,
    "THB": 35.0,
    "VND": 25000.0,
    "AED": 3.67,
    "SAR": 3.75,
    "EGP": 48.0,
    "KWD": 0.31,
    "BHD": 0.38,
    "OMR": 0.38,
    "QAR": 3.64,
    "JOD": 0.71,
    "LBP": 15000.0,
    "TND": 3.1,
    "DZD": 135.0,
    "MAD": 10.0,
    "NGN": 1500.0,
    "KES": 130.0,
    "PKR": 280.0,
    "BDT": 110.0,
    "NPR": 133.0,
    "UAH": 38.0,
    "KZT": 450.0,
    "UZS": 12500.0,
    "GEL": 2.7,
    "AZN": 1.7,
    "AMD": 390.0,
    "BYN": 3.3,
    "MDL": 18.0,
    "KGS": 88.0,
    "TJS": 10.8,
    "AUD": 1.43,
    "CAD": 1.37,
    "NZD": 1.71,
    "CHF": 0.79,
    "SEK": 9.36,
    "NOK": 9.72,
    "DKK": 6.47,
    "PLN": 3.68,
    "CZK": 21.17,
    "HUF": 337.85,
    "RON": 4.41,
    "BGN": 1.70,
    "HRK": 6.80,
    "RSD": 110.0,
    "ISK": 124.98,
}

mapping = {
    "US$": "USD",
    "$": "USD",
    "AED": "AED",
    "EGP": "EGP",
    "SAR": "SAR",
    "KR": "KRW",
    "₪": "ILS",
    "€": "EUR",
    "£": "GBP",
    "¥": "JPY",
    "₱": "PHP",
    "RM": "MYR",
    "Rp": "IDR",
    "₹": "INR",
    "LKR": "LKR",
    "IDR": "IDR",
    "TWD": "TWD",
    "HKD": "HKD",
}

region_default = {
    "TR": "TRY",
    "CN": "CNY",
    "DE": "EUR",
    "GB": "GBP",
    "BR": "BRL",
    "IN": "INR",
    "JP": "JPY",
    "KR": "KRW",
    "ID": "IDR",
    "MY": "MYR",
    "PH": "PHP",
    "TH": "THB",
    "VN": "VND",
    "AE": "AED",
    "SA": "SAR",
    "EG": "EGP",
    "KW": "KWD",
    "BH": "BHD",
    "OM": "OMR",
    "QA": "QAR",
    "JO": "JOD",
    "LB": "LBP",
    "TN": "TND",
    "DZ": "DZD",
    "MA": "MAD",
    "NG": "NGN",
    "KE": "KES",
    "PK": "PKR",
    "BD": "BDT",
    "LK": "LKR",
    "NP": "NPR",
    "UA": "UAH",
    "KZ": "KZT",
    "UZ": "UZS",
    "GE": "GEL",
    "AZ": "AZN",
    "AM": "AMD",
    "BY": "BYN",
    "MD": "MDL",
    "KG": "KGS",
    "TJ": "TJS",
    "AU": "AUD",
    "CA": "CAD",
    "NZ": "NZD",
    "CH": "CHF",
    "SE": "SEK",
    "NO": "NOK",
    "DK": "DKK",
    "PL": "PLN",
    "CZ": "CZK",
    "HU": "HUF",
    "RO": "RON",
    "BG": "BGN",
    "HR": "HRK",
    "RS": "RSD",
    "IS": "ISK",
}

