name: Run Steam Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync With Main Branch
        run: git pull origin main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install -r requirements.txt

      - name: Run scraper
        run: python steam_scrapper.py

      - name: Commit and Push updated CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/steam_games.csv
          git commit -m "Updated Steam data (3-hour intervals)"
          git push origin main
