name: Scrape Streaming Services Every 3 Hours

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python streaming_services_scrapper.py

      - name: Commit and push updated CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated Streaming Services data (3-hour intervals)" || echo "No Change"
          git pull --rebase origin main
          git push origin main
